name: vibe_tuner
description: >
  Aplikacja Flutter wyświetlająca utwory muzyczne na podstawie emocji
  wykrytych z twarzy lub wybranych ręcznie.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.1.4
  provider: ^6.1.2
  camera: ^0.11.0+2
  image_picker: ^0.8.7
  image: ^4.0.17
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.0.0
  http: ^1.5.0
  flutter_secure_storage: ^8.0.0
  http_parser: ^4.0.0
  path: ^1.8.2
  fl_chart: ^1.1.1
  url_launcher: ^6.3.0
  just_audio: ^0.9.40
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

  assets:
    - lib/assets/icons/
    - lib/assets/images/